# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8af2c8e0800b9dcf9e9be3d43377c2f5ea5dead459da71b6b1fddc59ab16bb8f6bf69dfc4306795f879189f35529886ffbb050668ad27a91d8acdefeabf07ef

test:
  secret_key_base: 51302e1f584f6c6dda1f80638cc202e680f49fb39ae5ac75af31bda8e2d1fbafc6c0cfa0ddb38453c8fbb3e23702f566bbae7a0d3845db8db175d18d9058fcd3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
